apiVersion: v1
kind: Pod
metadata: 
  name: multi-container-playground
spec:
  containers:
  - name: c1
    image: nginx:1.17.6-alpine
    env:
      - name: MY_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    volumeMounts:
    - name: storage
      mountPath: /my-vol
  
  - name: c2
    image: busybox:1.31.1
    command: ["sh", "-c", "while true; do date >> /my-vol/date.log; sleep 1; done"]
    volumeMounts:
    - name: storage
      mountPath: /my-vol

  - name: c3
    image: busybox:1.31.1
    volumeMounts:
    - name: storage
      mountPath: /my-vol
    command: ["tail", "-F", "/my-vol/date.log"]
  
  volumes:
  - name: storage
    emptyDir: {}