apiVersion: v1
kind: Pod
metadata:
  name: ready-if-service-ready2
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: nginx:1.23.3
    livenessProbe:
      exec:
        command: ['true']
      initialDelaySeconds: 5
      periodSeconds: 3
    readinessProbe:
      exec:
        command:
          - wget 
          - -T2
          - -O-
          - http://service-am-I-ready:80
      initialDelaySeconds: 15
      periodSeconds: 10
