---
apiVersion: v1
kind: Namespace
metadata:
  name: secret

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: secret
spec:
  containers:
  - name: busybox-task6
    image: busybox:1.31.1
    command: ["sleep", "3600"]
    env:
    - name: APP_USER
      valueFrom:
        secretKeyRef:
          name: secret2
          key: user
    - name: APP_PASS
      valueFrom:
        secretKeyRef:
          name: secret2
          key: pass
    volumeMounts:
    - name: strg
      mountPath: /tmp/secret1
      readOnly: true
  volumes:
  - name: strg
    secret:
      secretName: akzholse
   
---
apiVersion: v1
kind: Secret
metadata:
  name: akzholse
  namespace: secret

---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
  namespace: secret
type: Opaque
data:
  user: dXNlcjEK
  pass: MTIzNAo= 



