---
apiVersion: v1
kind: Namespace
metadata:
  name: project-hamster-akzhol

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processor
  namespace: project-hamster-akzhol

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: project-hamster-akzhol
  name: processor
rules:
- apiGroups: [""]
  resources: ["secrets", "configMaps"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: processor
  namespace: project-hamster-akzhol
subjects:
- kind: ServiceAccount
  name: processor
  
roleRef:
  kind: Role
  name: processor
  apiGroup: rbac.authorization.k8s.io
