apiVersion: v1
kind: Pod
metadata:
  name: ready-if-service-ready2
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: nginx:1.23.3
    livenessProbe:
      exec:
        command: ['true']
      initialDelaySeconds: 5
      periodSeconds: 3
    command: ["/bin/sh"]
    args: ["-c", "apt update && apt install wget -y && nginx -g 'daemon off;'"]
    readinessProbe:
      exec:
        command:
          - wget 
          - -T2
          - -O-
          - http://service-am-I-ready:80
      initialDelaySeconds: 20
      periodSeconds: 10

---
apiVersion: v1
kind: Pod
metadata:
  name: am-i-ready
  labels:
    id: cross-server-ready
spec:
  containers:
  - name: nginx
    image: nginx:1.16.1-alpine
    command: ["/bin/sh"]
    args: ["-c", "nginx -g 'daemon off;'"]

---
apiVersion: v1
kind: Service
metadata:
  name: service-am-i-ready
spec:
  selector:
    id: cross-server-ready
  ports:
  - name: http
    port: 80
    targetPort: 80